#![allow(dead_code)]
pub const LOCAL_PLAYER: u32 = 0x310ed68;
pub const GAME_TIME: u32 = 0x31081a8;
pub const OBJECT_MANAGER: u32 = 0x1870bd8;
pub const RENDERER: u32 = 0x3141584;
pub const UNDER_MOUSE_OBJECT: u32 = 0x24bfc24;
pub const VIEW_PROJ_MATRICES: u32 = 0x313e6a0;
pub const OBJECT_MAP_COUNT: u32 = 44;
pub const OBJECT_MAP_ROOT: u32 = 40;
pub const OBJECT_MAP_NODE_NET_ID: u32 = 16;
pub const OBJECT_MAP_NODE_OBJECT: u32 = 20;
pub const OBJECT_INDEX: u32 = 0x0008; // Dumper could not find this offset.
pub const OBJECT_TEAM: u32 = 0x0034; // Dumper could not find this offset.
pub const OBJECT_DIRECTION: u32 = 0x1BB0; // Dumper could not find this offset.
pub const OBJECT_POSITION: u32 = 0x01DC; // Dumper could not find this offset.
pub const OBJECT_DEAD: u32 = 0x021C; // Dumper could not find this offset.
pub const OBJECT_VISIBILITY: u32 = 0x0274; // Dumper could not find this offset.
pub const OBJECT_MANA: u32 = 0x029C; // Dumper could not find this offset.
pub const OBJECT_MAX_MANA: u32 = 0x02AC; // Dumper could not find this offset.
pub const OBJECT_INVULNERABLE: u32 = 0x03D4; // Dumper could not find this offset.
pub const OBJECT_TARGETABLE: u32 = 0x0D04; // Dumper could not find this offset.
pub const OBJECT_HEALTH: u32 = 0x0E74; // Dumper could not find this offset.
pub const OBJECT_MAX_HEALTH: u32 = 0x0E84; // Dumper could not find this offset.
pub const OBJECT_BONUS_ATTACK_DAMAGE: u32 = 0x12C4; // Dumper could not find this offset.
pub const OBJECT_ATTACK_DAMAGE: u32 = 0x134C; // Dumper could not find this offset.
pub const OBJECT_ARMOR: u32 = 0x1374; // Dumper could not find this offset.
pub const OBJECT_BONUS_ARMOR: u32 = 0x1378; // Dumper could not find this offset.
pub const OBJECT_MAGIC_RESIST: u32 = 0x137C; // Dumper could not find this offset.
pub const OBJECT_MOVEMENT_SPEED: u32 = 0x138C; // Dumper could not find this offset.
pub const OBJECT_ATTACK_RANGE: u32 = 0x1394; // Dumper could not find this offset.
pub const OBJECT_CHAMPION_NAME: u32 = 0x2BA4; // Dumper could not find this offset.
pub const HERO_INTERFACE: u32 = 0x1870c68;
pub const MINION_INTERFACE: u32 = 0x24bfab4;
pub const TURRET_INTERFACE: u32 = 0x3105acc;
pub const MISSILE_INTERFACE: u32 = 0x24bfa60;
pub const GAME_WINDOW_WIDTH: u32 = 12;
pub const GAME_WINDOW_HEIGHT: u32 = 16;
pub const GAME_VERSION: u32 = 0x1510f04;